# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b1c8759693d1dd05cb9acae4e65744d11c8f1b43d8ad9bdafeada19aa179b14bc763f1f0f08c068827b18a028b3dca11ce9cbd8556be17f70bc0920756f313fc

test:
  secret_key_base: 1ef8055db6333e858309467fc31deb69400584643a401d33b29d4c9f846ec4c42ed882c0eda37c49deeec8c0d131210f9bb021e32773fac3229d177db0e9f5ac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
